### ISSUE TITLE
more built in water color brush

### ISSUE THREAD

**Issue by Reaper10** [Deevad/deevad-krita-brushpresets#11]
I found more water color brush could consider building them into the default brush set.
https://github.com/vascoalexander/krita-watercolor-set
![Cover](https://user-images.githubusercontent.com/8137561/80821678-d3a32700-8b9e-11ea-82b1-b7886230a692.jpeg)

**Comment by Deevad** [comment]
Hi, thank you. I'll not do it. This brush were compatible for Krita 2.9 and a lot of settings changed. They probably still load in Krita but the result is far from the rendering the author designed for sure due to 2 major Krita version in between (3.0 and 4.0).

But! Ramon Miranda made a extension recently for Watercolor in future version of Krita that will be far superior to this set because it uses new feature. I reviewed it two weeks ago here https://invent.kde.org/kde/krita/-/merge_requests/299 :  I think it will be part Krita 4.3 release (soon).  

So, good news for watercolor, I close this issue.
